# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pcb',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('id', models.IntegerField()),
                ('date_prod', models.DateField(blank=True, null=True)),
                ('kind', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'pcb',
                'managed': True,
            },
        ),
    ]
